### ISSUE TITLE
plugin does not work for me

### ISSUE THREAD

**Issue by zork17** [wailuen/homebridge-sensibo-sky#10]
Hi,
I have 2 homebridge services installed on my Raspberry Pi. 
In one of them I have in the config.json:
		{
				"platform": "SensiboSky",
				"name": "Sensibo",
				"apiKey": "JxxxxxxxxxxxxxxxxxxxxxxxxxxxxT"
		},

When I ran the service, I get these sensibo related lines in the log:
Jul 29 10:10:12 RSBPI homebridge[7974]: [7/29/2017, 10:10:12 AM] [Sensibo] Initializing SensiboSky platform...
Jul 29 10:10:12 RSBPI homebridge[7974]: [7/29/2017, 10:10:12 AM] [Sensibo] Fetching Sensibo devices...

and that's it. I assume I need to see the devices...

**Comment by wailuen** [comment]
I suspect it is the apiKey issues. Cannot help unless I can replicate it. Did you try to disable one of homebridge services ?

**Comment by zork17** [comment]
I didn't try to disable the other homebridge because it has knx and all the lights in the house which everybody's using all the time. 
Is there a way to see more detailed debug messages?
Is there a way I can send you the api key so you can try it? I will change it later. 
When I created the api key in my sensibo account I gave it a name homebridge. Does this name matters?

**Comment by zork17** [comment]
fixed it. it was a problem with my email address.
Thanks

**Comment by wailuen** [comment]
Good to know..
