### ISSUE TITLE
Auto mode

### ISSUE THREAD

**Issue by dotdd** [wailuen/homebridge-sensibo-sky#17]
Hello, my AC has an auto mode where it determines using Heat or Cool by measuring the indoor and outdoor unit, which is more reliable then the Sensibo temp (as it appears higher then actual). Sensibo app does support the Auto mode so I wonder if it would be possible to have the Auto option map to the real Auto mode option?

**Comment by craigcullum** [comment]
I’d love to be able to hide the fan and set the fans permanently to 0% for Auto as with the Sensibo app and just use the temperature setting and mode to adjust the temperature. This is much better than the AI approach with my ACs.

**Comment by 00JohnD** [comment]
Is it me or it seems nobody ever answered dotdd's question...? I have the same issue here, I would like to use the AC's real auto mode and that doesn't seems to be possible with this plugin. 

Am I missing something?
