### ISSUE TITLE
Temperature adjustment automatically sets cooling mode

### ISSUE THREAD

**Issue by jsundgot** [wailuen/homebridge-sensibo-sky#2]
Great work on this, wailuen - really appreciate your contribution. I set up homebridge with this plugin running on a Raspberry Pi a couple of days ago, and everything appears to be stable and functional so far.

There is one thing I can't figure out, however. Every time I adjust the temperature on my A/C through Apple Home or Siri, the command issued through HomeKit not only sets the (requested) temperature, but also changes the mode to Cool. If I then manually adjust the mode to Heat, it sticks.

I tried setting the "ai" flag to false in config.json, even though I doubted this would have any impact, and sure enough it didn't.

Is setting the mode to Cool when temperature is adjusted done by design? If not, I'd be grateful for any assistance in troubleshooting the matter. I would of course also be happy to provide a log output if this would be helpful.

Alternatively, if this is done by design, would you consider changing the behaviour? Living somewhere cold, I almost never have use for the Cool mode so this adds an extra step every time I adjust my temperature manually, or set up an automation routine.

**Comment by wailuen** [comment]
Let me work on this over the weekend.

**Comment by jsundgot** [comment]
Works like a charm, thanks! Could I also add a feature request? As I mentioned in my original comment, I live somewhere cold, which means I literally never use the Cool mode of the A/C, but rather just conserve energy by turning the A/C off (and potentially open doors/windows) if it gets too hot.

How you updated the standard behaviour with setting Heat and Cool modes depending on whether temperature is respectively increased or decreased seems like an intelligent choice to me, and is probably a good fit for the vast majority of users.

However, since my use case is a little unusual, would it be possible to add a parameter that you could address from config.json, which would allow setting only the temperature and not alter the Off/Heat/Cool/Auto state at the same time?

For instance:

"autoState": true/false

**Comment by wailuen** [comment]
Could you elaborate a little more? I dun quite get you.

**Comment by jsundgot** [comment]
Of course. When I adjust the temperature, I would like _only_ the temperature, and not the Heat/Cool state, to be changed. For instance, if I adjust temperature from 23 degrees to 21 degrees, I don't want the state changing from Heat to Cool but just stay in Heat mode.

Put differently, I would like to always change the Heat/Cool state manually instead of automatically.

This request is probably uncommon (at least I think it is), which was why I suggested a parameter to allow for disabling changing the Heat/Cool state instead of this being default behaviour.

Hope this helps.

**Comment by Cloudore** [comment]
So you're trying to disable the feature he just implemented?

**Comment by jsundgot** [comment]
No. Previously, changing temperature also always set the state to 'Cool'. The feature that was just implemented (current) sets state to 'Heat' if temperature is increased, and to 'Cool' if temperature is decreased.

I think the current approach where states are changed depending on which direction temperature is adjusted is logical, and probably the best approach for the majority of users. However, since I'm not in this majority, I'm asking for a parameter that will make it possible to _only_ adjust temperature while leaving the state unchanged.

This will for instance let me maintain a 'Heat' state at all times, while someone living somewhere very warm could maintain a 'Cool' state at all times. Additionally, the needs of someone who wishes to let their A/C remain in an 'Auto' state at all times could be met as well.

Did that clear up things, @Cloudore?

**Comment by jsundgot** [comment]
@wailuen Could I ask whether you've had the chance to consider my request for a parameter that would let me adjust temperature only, without changing the Heat/Cool mode at all?

**Comment by wailuen** [comment]
Sorry that i had miss this. Could you open a new issue so that i can see when to work on it.

**Comment by jsundgot** [comment]
Of course, thanks a lot.
