### ISSUE TITLE
Temperature scale

### ISSUE THREAD

**Issue by EdiVip** [wailuen/homebridge-sensibo-sky#22]
Hello!

Is there any possibility to change range of the temperature in HomeKit in home bridge config file? for example in  My AC can handle temperature from 18'C to 30'C but on HomeKit I can set from 10'C to 38'C Of course my AC cannot set 10'C-17'C and 31'C-38'C temperature and do nothing :(

**Comment by wailuen** [comment]
Sorry. I do not think or capable to controlling the Home App range.
