### ISSUE TITLE
Adding 2 Sensibo Skys to the config file

### ISSUE THREAD

**Issue by fujitasenpai** [wailuen/homebridge-sensibo-sky#24]
Hi @wailuen I've been using your plug in since I got my 1st Sensibo Sky and have been using it without any issue.

I'm now adding a second Sensibo Sky to my home and I'm stuck at the config.json. Under "platforms" I already have a:
`
{
"platform":     "SensiboSky",
"name":         "Living Room Aircon",
"apiKey":       "oLh73MmToFxxxxxxxxxx",
}
`
I would like to add another one that's named "Dining Room Aircon" but no matter what I do I always get an error. Do you have any example on how the config.json should be written? 

Thanks a lot!

**Comment by Cloudore** [comment]
Hey @fujitasenpai, in theory, your API should be able to communicate to all your Sensibo devices.

In this case I would have you try to use your initial configuration, but remove the first API you created and replace it with a newly generated one. Remember you only need one API per account, not one per device.

Regards,
Izzat

**Comment by fujitasenpai** [comment]
Hi @Cloudore thanks for the information. I have done that but my original question was about the config.json itself.

The config.json I'm using currently is working fine, but I'm just curious if it's ok to have 2 "platforms" tag or instead if I can shorten it into 1 tag and have 2 Sensibos define in it. 

Here's what I have:

"platforms": [
        {
                "platform":     "SensiboSky",
                "name":         "Living Room Aircon",
                "apiKey":       "JWgtTLCxxxxxxxxxx",
                "timeLapse":    30,
                "ai":           false,
                "hideFan":      true,
                "hideHumidity": true,
                "fixedState" :  "manual"
        },
        {
                "platform": "TplinkSmarthome",
                "name": "Water Heater"
        }

   ],
"platforms": [
        {
                "platform":     "SensiboSky",
                "name":         "Dining Room Aircon",
                "apiKey":       "JWgtTLCxxxxxxxxxx",
                "timeLapse":    30,
                "ai":           false,
                "hideFan":      true,
                "hideHumidity": true,
                "fixedState" :  "manual"
        }
   ]


Thanks!

**Comment by fujitasenpai** [comment]
@Cloudore this does the trick, I just realize you don't even need to edit the config.json. Just change it with the new API key and Home app notice that there are actually 2 devices. I just change the name of the new Sensibo and now I'm controlling both aircons using Siri & scenes. Thanks!!
