### ISSUE TITLE
Use the Sensors in HomeKit Automation?

### ISSUE THREAD

**Issue by pbassham** [wailuen/homebridge-sensibo-sky#25]
I can see the humidity and temperature values in Homekit, but when I go to the Automation section, they are unavailable to use for the Automation triggers. 

Is there a reason for this? Or is it possible to enable the use of the Sensibo sensors somehow?

**Comment by Cloudore** [comment]
That is a limitation on the native Home.app

You'll be able to automate based on humidity with other applications such as the Eve elgato app

**Comment by pbassham** [comment]
Oh ok, thanks. That works.
