### ISSUE TITLE
 'This Accessory is not responding' homekit error

### ISSUE THREAD

**Issue by sharmacentral** [wailuen/homebridge-sensibo-sky#3]
Hi, 

First of all, thanks for keeping the plugin alive. When I use this, I keep getting the 'This Accessory is not responding' homekit error. 
Here is the log that I see:

6/20/2017, 12:31:23 AM] Loading 1 platforms...
[6/20/2017, 12:31:23 AM] [Sensibo] Initializing SensiboSky platform...
[6/20/2017, 12:31:23 AM] [Sensibo] Fetching Sensibo devices...
[6/20/2017, 12:31:23 AM] [Sensibo]  : AI State: true , RefreshCycle: 5000
[6/20/2017, 12:31:23 AM] [Sensibo] Device Added (Name: Family Room AC, ID:, Group: pods)
[6/20/2017, 12:31:23 AM] [Sensibo] Initializing platform accessory 'Family Room AC'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

┌────────────┐ 
│ XXX-XX-XXX │ 
└────────────┘ 

[6/20/2017, 12:31:24 AM] Homebridge is running on port 12345.
[6/20/2017, 12:32:18 AM] [Sensibo] Identify! (name: Family Room AC)

What could be missing? I am running homebridge on a mac with the 0.2.3 version of the plugin. The json.conf is:

{
    "bridge": {
        "name": "MacBridge",
        "username": "11:00:00:00:00:11",
        "port": 12345,
        "pin": "<removed>"
    },
    "platforms": [
        {
                "platform": "SensiboSky",
                "name": "Sensibo",
                "apiKey": "<removed>",
   		"timeLapse": 5,
   		"ai": true,
   		"hideHumidity": true
        }
    ]

Thanks in advance,
edit: The pin and the api-key were blanked out.

**Comment by wailuen** [comment]
Does other plugin work? I suspect it is the config at home bridge itself.

**Comment by sharmacentral** [comment]
pdlove's plugin gets me the same error as well. But other plugins (nest,liftmaster,tplink etc.) all work fine. I am going to see if I can run this on a linux box instead of mac osx 10.12.5.

**Comment by wailuen** [comment]
Hmm.. dun think it is Mac as I used my Mac for development and test before porting to the raspberry pi.

**Comment by sharmacentral** [comment]
Thanks - I guess this is neither a plugin issue nor a Mac issue. I get "Error at req: ECONNREFUSED" on my linux machine.

**Comment by wailuen** [comment]
This error is due to the sensibo server refused connection. It seem to happy when there are too many request at one go. The plugin will try again on the next cycle. Maybe can set the timeLapse to a higher number to minimise it.

**Comment by Cloudore** [comment]
timeLapse at 50s with first gen Sensibo and three pods here, it's been working smoothly since I incremented it.

**Comment by wailuen** [comment]
My Bridge config as below. Not sure if could be the problem

"bridge": {
        "name": "Macbridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51826,
        "pin": "001-00-001"
    },

I generated the username from http://www.miniwebtool.com/mac-address-generator/
I also used the default port 51826. Not sure if this may had been the problem.

**Comment by wailuen** [comment]
Close issued since it is not a plugin issue.

**Comment by sharmacentral** [comment]
Thanks for sharing the config - still no success for me. You are right - this is not a plugin issue. I will keep at it though. Thanks for your time on this.
