### ISSUE TITLE
Siri doesn't change the temperature.

### ISSUE THREAD

**Issue by ori324** [wailuen/homebridge-sensibo-sky#38]
hi,
Siri doesn't change the temperature.
it change only from the home app. 
if you say to her she doesn't change the temperature.

please fix.

thanks :)

**Comment by Cloudore** [comment]
@imerin fixed this, if I am not mistaken, in his Pull Request #36, you're going to have to clone that since this repository was abandoned.

Taking a shot at paging @wailuen for him to give someone else control over this.

**Comment by ori324** [comment]
How I do this? Thanks

**Comment by imerin** [comment]
@ori324 you can follow the instructions here https://github.com/wailuen/homebridge-sensibo-sky/pull/36#issuecomment-515884065

**Comment by wailuen** [comment]
> @imerin fixed this, if I am not mistaken, in his Pull Request #36, you're going to have to clone that since this repository was abandoned.
> 
> Taking a shot at paging @wailuen for him to give someone else control over this.

Sorry for disappearing... just merge the pull request. Anyone like to take over this repository?
