### ISSUE TITLE
Fan not working

### ISSUE THREAD

**Issue by Cloudore** [wailuen/homebridge-sensibo-sky#5]
New issue but related to what was done to accomodate the scenes in [here](https://github.com/wailuen/homebridge-sensibo-sky/issues/4) I think:

Fans are not working anymore in the home.app, manipulating a fan results in no change in Sensibo or the AC. What is weird is, they work perfectly normal in the ElGatoEve Homekit app.

What I did: rebooted my Pi, went to the Home.app, turned on my ac and tried to manipulate the fan on it. When it didn't work, I switched on and off my tv (to create a a way to differentiate in the log what is before and what is after). Then, after that, I opened the ElGatoEve app and succesfully manipulated the fan from it.

>Jul 01 06:51:48 raspberrypi homebridge[522]: [7/1/2017, 6:51:48 AM] [Sensibo] Zack State change set, current ACstate: cool  new state: 2
Jul 01 06:51:48 raspberrypi homebridge[522]: [7/1/2017, 6:51:48 AM] [Sensibo] Zack  - Submit state change: New state:  cool On/Off Status: true
Jul 01 06:51:49 raspberrypi homebridge[522]: [7/1/2017, 6:51:49 AM] [Sensibo] Changed status (name: Zack, roomTemp: 16, on: true, mode: cool, targetTemp: 25, speed: auto)
Jul 01 06:51:52 raspberrypi homebridge[522]: [7/1/2017, 6:51:52 AM] [Sensibo] [DEBUG temp]  Zack  Cur Target temp: 25  new targetTemp:  20
Jul 01 06:51:52 raspberrypi homebridge[522]: [7/1/2017, 6:51:52 AM] [Sensibo] Zack  Submit new target temperature:  20
Jul 01 06:51:52 raspberrypi homebridge[522]: [7/1/2017, 6:51:52 AM] [Sensibo] Changed status (name: Zack, roomTemp: 16, on: true, mode: heat, targetTemp: 20, speed: auto)
Jul 01 06:51:53 raspberrypi homebridge[522]: [7/1/2017, 6:51:53 AM] [Sensibo] [DEBUG temp]  Zack  Cur Target temp: 20  new targetTemp:  19
Jul 01 06:51:53 raspberrypi homebridge[522]: [7/1/2017, 6:51:53 AM] [Sensibo] Zack  Submit new target temperature:  19
Jul 01 06:51:53 raspberrypi homebridge[522]: [7/1/2017, 6:51:53 AM] [Sensibo] Changed status (name: Zack, roomTemp: 16, on: true, mode: heat, targetTemp: 19, speed: auto)
Jul 01 06:52:16 raspberrypi homebridge[522]: [7/1/2017, 6:52:16 AM] [Sensibo] [DEBUG temp]  Zack  Cur Target temp: 25  new targetTemp:  21
Jul 01 06:52:16 raspberrypi homebridge[522]: [7/1/2017, 6:52:16 AM] [Sensibo] Zack  Submit new target temperature:  21
Jul 01 06:52:17 raspberrypi homebridge[522]: [7/1/2017, 6:52:17 AM] [Sensibo] [DEBUG temp]  Zack  Cur Target temp: 21  new targetTemp:  20
Jul 01 06:52:17 raspberrypi homebridge[522]: [7/1/2017, 6:52:17 AM] [Sensibo] Zack  Submit new target temperature:  20
Jul 01 06:52:17 raspberrypi homebridge[522]: [7/1/2017, 6:52:17 AM] [Sensibo] Changed status (name: Zack, roomTemp: 21.8, on: true, mode: cool, targetTemp: 20, speed: auto)
Jul 01 06:52:17 raspberrypi homebridge[522]: [7/1/2017, 6:52:17 AM] [Sensibo] [DEBUG temp]  Zack  Cur Target temp: 20  new targetTemp:  19
Jul 01 06:52:17 raspberrypi homebridge[522]: [7/1/2017, 6:52:17 AM] [Sensibo] Zack  Submit new target temperature:  19
Jul 01 06:52:18 raspberrypi homebridge[522]: [7/1/2017, 6:52:18 AM] [Sensibo] Changed status (name: Zack, roomTemp: 21.8, on: true, mode: cool, targetTemp: 19, speed: auto)
Jul 01 06:52:26 raspberrypi homebridge[522]: [7/1/2017, 6:52:26 AM] [Sensibo] Changed status (name: Zack, roomTemp: 21.8, on: true, mode: cool, targetTemp: 19, speed: auto)
Jul 01 06:52:34 raspberrypi homebridge[522]: [7/1/2017, 6:52:34 AM] [Sensibo] [AI DEBUG] Fan Setting: Z4JU2ZVy_ : Sat Jul 01 2017 06:52:34 GMT+0000 (UTC) :NewFanSpeed: medium  CurrentFanLevel: auto
Jul 01 06:52:35 raspberrypi homebridge[522]: [7/1/2017, 6:52:35 AM] [Sensibo] [AI DEBUG] Fan Setting: Z4JU2ZVy_ : Sat Jul 01 2017 06:52:35 GMT+0000 (UTC) :NewFanSpeed: high  CurrentFanLevel: medium
Jul 01 06:52:35 raspberrypi homebridge[522]: [7/1/2017, 6:52:35 AM] [Sensibo] Unsucessful setting: Zack : Sat Jul 01 2017 06:52:35 GMT+0000 (UTC) :Reverting to previous state:  auto
Jul 01 06:52:35 raspberrypi homebridge[522]: [7/1/2017, 6:52:35 AM] [Sensibo] Unsucessful setting: Zack : Sat Jul 01 2017 06:52:35 GMT+0000 (UTC) :Reverting to previous state:  medium
Jul 01 06:52:42 raspberrypi homebridge[522]: [7/1/2017, 6:52:42 AM] [Sensibo] [AI DEBUG] Fan Setting: Z4JU2ZVy_ : Sat Jul 01 2017 06:52:42 GMT+0000 (UTC) :NewFanSpeed: medium_high  CurrentFanLevel: high
Jul 01 06:52:43 raspberrypi homebridge[522]: [7/1/2017, 6:52:43 AM] [Sensibo] Unsucessful setting: Zack : Sat Jul 01 2017 06:52:43 GMT+0000 (UTC) :Reverting to previous state:  high
Jul 01 06:52:50 raspberrypi homebridge[522]: [7/1/2017, 6:52:50 AM] [Shutter Estudio] Requested CurrentPosition: 100
Jul 01 06:52:50 raspberrypi homebridge[522]: [7/1/2017, 6:52:50 AM] [Estudio] Requested CurrentPosition: 100
Jul 01 06:52:52 raspberrypi homebridge[522]: [7/1/2017, 6:52:52 AM] [Television] received on command: 1
Jul 01 06:52:54 raspberrypi homebridge[522]: [7/1/2017, 6:52:54 AM] [Television] No response from TV
Jul 01 06:52:54 raspberrypi homebridge[522]: [7/1/2017, 6:52:54 AM] [Television] attempting wake
Jul 01 06:52:54 raspberrypi homebridge[522]: [7/1/2017, 6:52:54 AM] [Television] wake request sent successfully
Jul 01 06:52:55 raspberrypi homebridge[522]: [7/1/2017, 6:52:55 AM] [Television] received on command: 0
Jul 01 06:52:55 raspberrypi homebridge[522]: [7/1/2017, 6:52:55 AM] [Television] sending power key
Jul 01 06:52:56 raspberrypi homebridge[522]: [7/1/2017, 6:52:56 AM] [Television] websocket connect
Jul 01 06:52:56 raspberrypi homebridge[522]: [7/1/2017, 6:52:56 AM] [Television] successfully powered off tv
Jul 01 06:52:57 raspberrypi homebridge[522]: [7/1/2017, 6:52:57 AM] [Television] websocket closed
Jul 01 06:53:13 raspberrypi homebridge[522]: [7/1/2017, 6:53:13 AM] [Sensibo] [AI DEBUG] Fan Setting: Z4JU2ZVy_ : Sat Jul 01 2017 06:53:13 GMT+0000 (UTC) :NewFanSpeed: low  CurrentFanLevel: auto
Jul 01 06:53:13 raspberrypi homebridge[522]: [7/1/2017, 6:53:13 AM] [Sensibo] [AI DEBUG] Fan Setting: Z4JU2ZVy_ : Sat Jul 01 2017 06:53:13 GMT+0000 (UTC) :NewFanSpeed: medium_high  CurrentFanLevel: low
Jul 01 06:53:13 raspberrypi homebridge[522]: [7/1/2017, 6:53:13 AM] [Sensibo] [AI DEBUG] Fan Setting: Z4JU2ZVy_ : Sat Jul 01 2017 06:53:13 GMT+0000 (UTC) :NewFanSpeed: high  CurrentFanLevel: medium_high
Jul 01 06:53:13 raspberrypi homebridge[522]: [7/1/2017, 6:53:13 AM] [Sensibo] Unsucessful setting: Zack : Sat Jul 01 2017 06:53:13 GMT+0000 (UTC) :Reverting to previous state:  low
Jul 01 06:53:13 raspberrypi homebridge[522]: [7/1/2017, 6:53:13 AM] [Sensibo] Unsucessful setting: Zack : Sat Jul 01 2017 06:53:13 GMT+0000 (UTC) :Reverting to previous state:  auto
Jul 01 06:53:32 raspberrypi homebridge[522]: [7/1/2017, 6:53:32 AM] [Sensibo] Changed status (name: Zack, roomTemp: 21.9, on: true, mode: cool, targetTemp: 19, speed: high)

p.d: I tried the good morning scene on this app to see if it would work properly as well, worked well the first 2 times then failed the 3rd.

Thanks again as always for the work on the plug in.

edit: This was supposed to be a comment on the existing issue thread, I uploaded a new issue by mistake

edit2: This is after reverting AI back to false and rebooting.

**Comment by wailuen** [comment]
Turn the Ai to false to take control of the fan. Sorry, did not have time to debug this week. Will see what I can do next week.

**Comment by Cloudore** [comment]
Ai was set to false in the json during this

No worries its your plugin

**Comment by Cloudore** [comment]
Had the fan work twice for the first time in a while today, then start failing again afterwards, log clip of the instance:

Jul 13 02:46:36 raspberrypi homebridge[1128]: [7/13/2017, 2:46:36 AM] [Sensibo] [AI DEBUG] Fan Setting: Z4JU2ZVy_ : Thu Jul 13 2017 02:46:36 GMT+0000 (UTC) :NewFanSpeed: medium  CurrentFanLevel: low
Jul 13 02:46:36 raspberrypi homebridge[1128]: [7/13/2017, 2:46:36 AM] [Sensibo] [AI DEBUG] Fan Setting: Z4JU2ZVy_ : Thu Jul 13 2017 02:46:36 GMT+0000 (UTC) :NewFanSpeed: high  CurrentFanLevel: medium
Jul 13 02:46:36 raspberrypi homebridge[1128]: [7/13/2017, 2:46:36 AM] [Sensibo] Unsucessful setting: Zack : Thu Jul 13 2017 02:46:36 GMT+0000 (UTC) :Reverting to previous state:  low
Jul 13 02:46:36 raspberrypi homebridge[1128]: [7/13/2017, 2:46:36 AM] [Sensibo] Unsucessful setting: Zack : Thu Jul 13 2017 02:46:36 GMT+0000 (UTC) :Reverting to previous state:  medium

**Comment by wailuen** [comment]
Usually, when it is unsucessful, it is due to sensible server not responding positively to the request. And that happen when there is too many request to the sensible server. 

Could you try again like in 30mins?

**Comment by wailuen** [comment]
Hi Cloudore, Is it working still ?

**Comment by Cloudore** [comment]
Sorry removed the fan from my set-up, since it seems this was an issue only on my side I'll go ahead and close this issue.
