### ISSUE TITLE
Parameter for temperature only?

### ISSUE THREAD

**Issue by jsundgot** [wailuen/homebridge-sensibo-sky#7]
Would it be possible to add a parameter to config.json to disable the automatic Cool/Heat mode adjustment, so that when you adjust temperature only temperature is adjusted, and the Cool/Heat mode is left entirely to manual control?

**Comment by wailuen** [comment]
Of course. Sorry that I had not been able to seat down to work on this yet.

**Comment by jsundgot** [comment]
Take all the time you need - I'm just grateful you're contributing :)

**Comment by wailuen** [comment]
Added "fixedState" parameter. Please test as I did not test it extensively. Value accepted are "cool" or "heat" or "auto". In your case, set it to "cool" permanently. Version 0.4.0

**Comment by jsundgot** [comment]
Looks good for now, will provide feedback when I've had it running a while longer. Thanks a lot!

**Comment by siavashvj** [comment]
I just tried it (fixedState:Cool). But combined with ai:true the fan speed is much more aggressive. With ai:false and fixedState:auto the fan speed is much smoother (and less aggressive).
