### ISSUE TITLE
Temperature Scale/Unit Configurable

### ISSUE THREAD

**Issue by EZtheOG** [wailuen/homebridge-sensibo-sky#8]
So, I see in that the Temperature Unit is hard coded to Celsius (forgive me if I am wrong as I don't read JavaScript too well) and I think this should be something that is configurable via config.json

https://github.com/wailuen/homebridge-sensibo-sky/blob/master/accessories/pods.js#L60

So, while I was hacking away I did try to add this:
`this.tempUnit = config["tempUnit"];`
and do a 
`that.state.temperatureUnit = device.tempUnit // "C";`

but I was unsure if I could add the logic to the fuction:
`sensibo.getPods(that.log, function (devices)`
 
But, I don't know maybe this is not something you can get from the Sensibo API? This is all one step over my head but I think this would be a good addition to make it so that the Temperature Unit can be dynamically passed as opposed to hard coded.

**Comment by wailuen** [comment]
The temperature unit is coming from sensibo. So u need to set it using the sensibo app.

**Comment by EZtheOG** [comment]
Really? This isn't something that can be passed?
