### ISSUE TITLE
hideFan parameter

### ISSUE THREAD

**Issue by Cloudore** [wailuen/homebridge-sensibo-sky#9]
The fan as HomeKit currently supports it, and because of that, the way it is integrated in this plug-in, its somewhat confusing for guests and not very clean and Apple-like. I myself always use the same Fan speed(100%) and would like to not have the fan devices on my page, while maintaining AI to false.

If this is something that can be done, I'm sure some people would appreciate it, I would surely.

As usual, thanks for the plug-in.

**Comment by wailuen** [comment]
Added "hideFan" parameter. Please test as I did not test it extensively. Need to set "ai" to false or just dun configure "ai" for this to work. Version 0.4.0

**Comment by Cloudore** [comment]
Hey Waliuen,

I had to create my fork(https://github.com/Cloudore/homebridge-sensibo-sky) out of one of your the forks of your plug in(it already hid the fans), because the Null Check was really messing with my set-up (Sensible devices were all resetting everyday).

Interestingly enough, in leoneleone's fork(https://github.com/leoneleone/homebridge-sensibo-sky) the scenes work perfectly, no false on's or off's, it might help you fix this one since it's the main Sensibo plug-in and I'm sure a lot of people would appreciate it.

Thank you for the hard work in the plug-in! If you can do something about the Null check I'll move back to the main.

Regards
